### PR TITLE
Autopilot

### PR DESCRIPTION
**Pull request by dwelc**
New single cluster K8s script on GCP with AutoPilot installed, AutoPilot Rules configured and postgres benchmark deployment ready to be scaled up.

### CODE REVIEW

**Comment by grdnrio** [comment]
I don't know how Google Cloud works, but is this a hardcoded path to a credentials file?

https://github.com/grdnrio/pwx-deploy/blob/766f05bd252fb81c36b02128651d39b56a37008e/kubernetes/autopilot/main.tf#L13

**Comment by grdnrio** [comment]
Same with these https://github.com/grdnrio/pwx-deploy/blob/766f05bd252fb81c36b02128651d39b56a37008e/kubernetes/autopilot/variables.tf#L35-L43

**Comment by grdnrio** [comment]
I put demo apps in this directory https://github.com/grdnrio/pwx-deploy/tree/766f05bd252fb81c36b02128651d39b56a37008e/apps - could Cockroach and Kafka be added here? Perhaps this needs to be rethought though as this project has grown quite a bit.

**Comment by dwelc** [comment]
Ok, I think this is ready now. Kafka folder still a WIP but credentials removed for all.

**Pull request merged**
